account/urls.py
from django.urls import path,include
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import PasswordResetConfirmView,\
    PasswordResetCompleteView,PasswordResetView,PasswordResetDoneView
app_name='account'

# all url patterns for this app mostly contains the login,signup,reset,forget urls
urlpatterns=[
    path('login',LoginHelpView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('',home,name='home'),
    path('signup/<slug:slug>',SignUpView.as_view(),name='signup'),
    path('reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('password_reset_done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete')
]

management/urls.py
from django.urls import path

from .views import *
app_name='management'

urlpatterns=[
    path('',PropertyHome,name='admin_home'),
    path('list-properties/',PropertyList.as_view(),name='All'),
    path('list-properties-approve-admin/',PropertyList.as_view(),name='Approve'),
    path('list-properties-sold-admin/', PropertyList.as_view(), name='Sold'),
    path('list-properties-reject-admin/', PropertyList.as_view(), name='Reject'),
    path('list-properties-pending-admin/', PropertyList.as_view(), name='Pending'),
    path('list-property-houses-admin/',TypeProperty.as_view(),name='Houses'),
    path('list-property-plot-admin/', TypeProperty.as_view(), name='Plot'),
    path('list-property-Commercial-admin/', TypeProperty.as_view(), name='Commercial'),
    path('admin-approve/<int:pk>/',AdminApprovalProperty.as_view(),name='approve'),
    path('admin-reject/<int:pk>/',AdminApprovalProperty.as_view(),name='reject'),
    path('admin-sold-property/<int:pk>/',AdminApprovalProperty.as_view(),name='sold'),
    path('admin-delete/<int:pk>/',DeleteView.as_view(),name='delete'),
    path('seller-list/',PersonList.as_view(),name='seller'),
    path('buyer-list/',PersonList.as_view(),name='buyer'),
    # path('search/',request1,name='nothing')
]

realEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler500,handler404
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('seller/',include('seller.urls')),
    path('admin-dashboard/',include('management.urls')),
    path('',include('django.contrib.auth.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from .views import *
app_name='seller'

urlpatterns=[
    path('passwords-change/',PasswordsChange.as_view(),name='passwords'),
    path('sellercreate/',SellerCreate.as_view(),name='create_property'),
    path('list-property-approved/',SellerListSold.as_view(),name='Approve'),
    path('list-property-pending/',SellerListSold.as_view(),name='pending'),
    path('list-property-not-approved/',SellerListSold.as_view(),name='Reject'),
    path('seller-home/',SellerHome.as_view(),name='seller_home'),
    path('list-sold-property/',SellerListSold.as_view(),name='Sold'),
    path('buyer-home/', BuyerHome.as_view(), name='buyer_home'),
    path('buyer-list-house/',BuyerListPropertiesHouese.as_view(),name='house'),
    path('buyer-list-plot/',BuyerListPropertiesHouese.as_view(),name='plot'),
    path('buyer-list-rent/',BuyerListPropertiesHouese.as_view(),name='rent'),
    path('buyer-list-commercial/',BuyerListPropertiesHouese.as_view(),name='commercial'),
    path('property-detail/<int:pk>/',DetailProperty.as_view(),name='detail'),
    path('buyer-property-detail/<int:pk>/',DetailProperty1.as_view(),name='detail1'),
    path('accepting/',ApprovalView.as_view(),name='redirect'),
    path('mail-sent/',index,name='index')

]

seller/models.py
from django.db import models
import datetime
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator

# Create your models here.
user = get_user_model()


# a general seller model of property
class SellerProperty(models.Model):
    alphanumeric = RegexValidator(r'^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')

    by = models.ForeignKey(user, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.CharField(max_length=100, default='1 million')
    unit_choice = [('Square feet', 'square feet'),
                   ('Square meter', 'square meter'),
                   ('Square Yard', 'Square Yard'),
                   ('Marla', 'marla'),
                   ('Kanal', 'kanal')]
    size = models.PositiveIntegerField()
    unit = models.CharField(choices=unit_choice, max_length=12)
    bedrooms = models.PositiveIntegerField()
    bathroom = models.PositiveIntegerField()
    image_house = models.ImageField(upload_to='property', default='property/c2.jpg')
    purpose_choice = [('Sale', 'sale'), ('Rent', 'rent')]
    purpose = models.CharField(choices=purpose_choice, max_length=4)
    type_choices = [('Plot', 'plot'), ('Commercial', 'commercial'), ('House', 'house')]
    type = models.CharField(max_length=10, choices=type_choices)
    city = models.CharField(max_length=30, validators=[alphanumeric])
    sector = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now=True)

    # ordering the model objects
    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.title + ',' + str(self.price)

    # getting the photo url
    def get_photo_url(self):
        if self.image_house and hasattr(self.image_house, "url"):
            return self.image_house.url


# approval model for the property
class Approve(models.Model):
    request_choices = [('Approve', 'Approve'), ('Reject', 'Reject'), ('Sold', 'Sold'), ('Pending', 'pending')]
    request_approval = models.CharField(choices=request_choices, max_length=10, default='pending')
    approval = models.ForeignKey(SellerProperty, on_delete=models.CASCADE, related_name='approval_seller')

    def __str__(self):
        return 'Approval detail fo this property title: ' + self.approval.title

    def seller_title(self):
        return self.approval.title

seller/forms.py
from .models import *
from django import forms

# property creation form
class SellerForm(forms.ModelForm):
    class Meta:
        model = SellerProperty
        exclude = ('by',)


class Contactform(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    message = forms.CharField(max_length=254)

seller/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import *
from .models import *
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.urls import reverse_lazy
from django.urls import resolve
from django.core.mail import send_mail
from django.contrib.auth.views import PasswordChangeView, PasswordChangeForm
from django.conf import settings
from django.core.exceptions import ValidationError


# Create your views here.

# password changing view
class PasswordsChange(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'seller/password.html'
    success_url = reverse_lazy('seller:seller_home')


# this is for the contact form
def index(request):
    if request.method == 'POST':
        message = request.POST['message']
        email = request.POST['email']
        send_mail('Contact form',
                  message,
                  email,
                  [settings.EMAIL_HOST_USER],
                  fail_silently=False
                  )
        return HttpResponseRedirect(reverse_lazy('seller:index'))
    ctx = Contactform()
    return render(request, 'seller/contactform.html', {'form': ctx})


# seller property creation view
class SellerCreate(LoginRequiredMixin, generic.CreateView):
    form_class = SellerForm
    template_name = 'seller/sellercreate.html'
    success_url = reverse_lazy('seller:redirect')
    login_url = 'account:login'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.by = self.request.user
        self.object.save()
        return super(SellerCreate, self).form_valid(form)


# redirecting user to this view after creation of property to set the approval instance of the particular property to pending
class ApprovalView(generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('seller:seller_home')

    def get(self, request, *args, **kwargs):
        x = SellerProperty.objects.count()
        p = SellerProperty.objects.all()
        Approve.objects.create(request_approval='pending', approval_id=p[0].id)
        return super().get(request, *args, **kwargs)


# seller list of property
class SellerListSold(generic.ListView, LoginRequiredMixin):
    model = Approve
    template_name = 'seller/list_sold_property.html'
    context_object_name = 'sold_list'

    def get_queryset(self):
        print(SellerProperty.objects)
        current_url = resolve(self.request.path_info).url_name
        return Approve.objects.filter(request_approval=current_url, approval__by=self.request.user).order_by(
            '-approval__timestamp')

    def get_context_data(self, *args, **kwargs):
        current_url = resolve(self.request.path_info).url_name
        ctx = super(SellerListSold, self).get_context_data(*args, **kwargs)
        ctx['dynamic'] = current_url
        return ctx


# seller property home
class SellerHome(generic.TemplateView, LoginRequiredMixin):
    template_name = 'seller/seller_extension.html'


# buyers home page
class BuyerHome(generic.TemplateView, LoginRequiredMixin):
    template_name = 'seller/buyer_home.html'


# buyer list of property
class BuyerListPropertiesHouese(LoginRequiredMixin, generic.ListView):
    model = Approve
    template_name = 'seller/list_buyer_property.html'
    context_object_name = 'buyer_list'

    def get_queryset(self):
        current_url = resolve(self.request.path_info).url_name
        if current_url == 'rent':
            return Approve.objects.filter(request_approval='Approve', approval__purpose__iexact=current_url).order_by(
                '-approval__timestamp')
        else:
            return Approve.objects.filter(request_approval='Approve', approval__type__iexact=current_url).order_by(
                '-approval__timestamp')


# details of property in seller interface
class DetailProperty(LoginRequiredMixin, generic.DetailView):
    model = SellerProperty
    template_name = 'seller/detail_property.html'
    context_object_name = 'detail'


# details of property in buyers interface
class DetailProperty1(LoginRequiredMixin, generic.DetailView):
    model = SellerProperty
    template_name = 'seller/detail_property_buyer.html'
    context_object_name = 'detail'

seller/templates/seller/buyer_home.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% bootstrap_javascript  %}
{% bootstrap_jquery %}
{% bootstrap_css %}

<html>
<head>
    <link rel="stylesheet" href="{% static 'css/seller.css' %}">

</head>
<body>
<div id="buyer-home">
<div id="transparent">
   <div class="navbar ">
        <h1 id="h1" style="width: 70%;margin: auto">REMS</h1>
       {% if user.is_staff %}
       <p class="m-0 p-3 font-weight-bold get-display"><a href="{% url 'management:admin_home' %}">Admin</a></p>
       {% endif %}
        <p class="m-0 p-3 font-weight-bold get-display"><a href="{% url 'seller:passwords' %}">Change Password</a></p>
       <p class="m-0 p-3 mr-5 font-weight-bold get-display"><a href="{% url 'account:logout' %}">Logout</a></p>
    </div>
   <div class="navbar p-2 row m-0 get-display" style="background-color: rgba(124,122,122,.525);" >
       <h3 id="sell-set" class="text-right col-sm-2">Buy          ></h3>
        <h6 class="m-0 p-2 ml-4 col-sm-1.5"><a href="{% url 'seller:house' %}">Houses</a></h6>
        <h6 class="m-0 p-2 ml-4 col-sm-1.5" ><a href="{% url 'seller:plot' %}">Plots</a></h6>
        <h6 class="m-0 p-2 ml-4 col-sm-1.5"><a href="{% url 'seller:commercial' %}">Commercial</a></h6>
       <h6 class="m-0 p-2 ml-5 col-sm-1.5"><a href="{% url 'seller:rent' %}">Rent</a></h6>
       <h6 id="switch" class="m-0 p-2 col-md-6 text-right"><a href="{% url 'seller:seller_home' %}">
           Switch to Seller mode</a></h6>
   </div>

    <div style="width:fit-content;background-color: white;color:black;border-radius: 8px;position:sticky;top: 5%;z-index: 2"
         class="ml-5">

    <h3 id="btn-1" style="font-size: 30px" class="p-2 ">
        Menu
        <img src=../../../media/css_styles/list-ul-solid.svg alt="list" style="height: 40px">
    </h3>
    </div>
    <div class="row m-0 fade-out" style="min-height:110vh" id="side-menu">
        <div class="col-sm-10 bg-dark p-5" >
        <div style="display: flex">
            <h1 class="m-0 p-5" style="width: 90%">REMS</h1>
            <h3 class="p-5"><span style="font-size: 30px" id="btn" class=" p-3 btn btn-danger">X</span></h3>
        </div>

        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:house' %}">Houses</a></h6>
        <h6  class="m-0 p-5 border-bottom" ><a href="{% url 'seller:plot' %}">Plots</a></h6>
        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:commercial' %}">Commercial</a></h6>
        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:rent' %}">Rent</a></h6>
        <h6 class="m-0 p-5 border-bottom">
            <a href="{% url 'seller:seller_home' %}">Switch to Seller mode</a></h6>
       {% if user.is_staff %}
           <h6 class="m-0 p-5 border-bottom"><a href="{% url 'management:admin_home' %}">Admin</a></h6>
       {% endif %}
        <h6 class="m-0 p-5 border-bottom"><a href="{% url 'seller:passwords' %}">Change password</a></h6>
       <h6 class="m-0 p-5 border-bottom"><a href="{% url 'account:logout' %}">Logout</a></h6>

        </div>
    </div>




{% block buyer_body %}
    <div class="container mt-5 text-center" >
        <h1>Welcome to my REMS</h1>
        <h1>Start browsing now to get your dream house!</h1>
    </div>
{% endblock %}
</div>
</div>
<div class="bg-dark p-4" style="color: white ">
    <div class="row m-0">
        <div class="col-lg-6">
            <h2 class="font2">Connect with us!</h2>
            <img id="footer-icon" src=../../../media/css_styles/facebook-brands.svg alt="fb">
            <img id="footer-icon" class="ml-3 mr-3" src=../../../media/css_styles/twitter-brands.svg alt="tw">
            <img id="footer-icon" src=../../../media/css_styles/github-brands.svg alt="git">

{#            <i class="fab fa-facebook" style="font-size: xx-large"></i>#}
{#            <i class="fab fa-twitter ml-3 mr-3" style="font-size: xx-large"></i>#}
{#            <i class="fab fa-github" style="font-size: xx-large"></i>#}
            <h2 class="mt-3 font1">About us!</h2>
            <p class="font3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aut dicta doloremque eos, maiores nisi totam? Accusantium, amet atque autem consectetur deleniti expedita explicabo ipsum magni porro quisquam vero voluptatem.</p>
        </div>
        <div class="col-lg-6">
            <h2 class="font1">Need help!</h2>
            <h3 class="font2">Fill out this <a style="color:dodgerblue;" href="{% url 'seller:index' %}">form</a> and we'll get back to you ASAP</h3>
            <div class="row m-0 mt-3">
                 <div class="col-sm-6">
                    <h4 class="font2">Contact us at</h4>
                    <p class="font3">923115186xxx</p>
                </div>

                <div class="col-sm-6">
                    <h4 class="font2">Email us at</h4>
                    <p class="font3">configteam@netlify.com</p>
                </div>
            </div>
        </div>
    </div>
    <div class="m-0 mt-4 border-top">
        <p class="m-0 text-center p-3 font3">All font icons are property of fontawesome <a href="https://fontawesome.com/">Visit them here</a></p>
    </div>
    <div class="border-top p-3">
        <p class="text-center font3">Copyright &copy;</p>
    </div>
</div>

<script src="../../../static/js/index.js"></script>


</body>
</html>

seller/templates/seller/contactform.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_jquery %}
{% bootstrap_javascript %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/seller.css' %}">
</head>
<body>
    <form action="" method="POST" class="container mt-5 p-5 font-weight-bold border rounded"  style="width: 40%;margin: auto">
        {% csrf_token %}
        <legend class="text-center"><h2>Contact form</h2></legend>
        {% bootstrap_form form %}
        <input type="submit" value="Send" class="btn btn-success" style="width: 100%">

        <div class="mt-3 p-3 row m-0">
            <h4 class="col-sm-6 "><a style="color: black" href="{% url 'seller:buyer_home' %}">Buyer Home</a></h4>
            <h4 class="col-sm-6 text-right"><a style="color: black" href="{% url 'seller:buyer_home' %}">Seller Home</a></h4>
        </div>
    </form>

</body>
</html>

seller/templates/seller/detail_property.html
{% extends 'seller/detail_extensio.html' %}
{% load humanize %}
{% block detail_block %}

    <div class="p-2 border-bottom mx-auto row detail" style="width: 50%;">
    {% if user.is_staff %}
        <h3 class="col-sm-2 font" ><a href="{% url 'management:admin_home' %}">Back</a></h3>
        <h3 class="col-sm-3 font"><a href="{% url 'management:delete'  detail.pk  %}">Delete</a></h3>
        <h3 class="col-sm-2 font"><a href="{% url 'management:sold' detail.pk %}">Sold</a></h3>
        <h3 class="col-sm-3 font"><a href="{% url 'management:approve' detail.pk %}">Approve</a></h3>
        <h3 class="col-sm-2 font"><a href="{% url 'management:reject' detail.pk %}">Reject</a></h3>
    {% endif %}

    </div>
    <div class="container" style="width: fit-content" id="width">
        <h3 class="font">{{ detail.title }}</h3>
        <img src="{{ detail.get_photo_url }}"class="mt-3" id="detail-img" alt="">
        <div class="row p-2 m-0" style="background-color: rgba(169,169,169,0.9)">
            <div class="col-sm-5">
                <h3 class="m-0 font">PKR: {{ detail.price }}</h3>
            </div>
            <div class="col-sm-7" id="font-s">
                <img src="../../../media/css_styles/bath-solid.svg" id="footer-icon1"  alt="">
                <span class=" ml-2 mr-3" style="font-size: x-large">{{ detail.bathroom }}</span>
                <img src="../../../media/css_styles/bed-solid.svg" id="footer-icon2" alt="">
                <span class=" ml-2 mr-3" style="font-size: x-large">{{ detail.bedrooms }}</span>
                <img src="../../../media/css_styles/ruler-combined-solid.svg" id="footer-icon1"   alt="">
                <span class="m-0 ml-1" style="font-size: x-large">{{ detail.size }} {{ detail.unit }}</span>            </div>
        </div>
        <h3 class="text-center bg-white p-2 mt-2">Overview</h3>
        <div class="row p-4 m-0 border-bottom" style="background-color: rgba(169,169,169,0.9)">
            <div class="col-lg-6">
                <h5>Type: {{ detail.type }}</h5>
                <h5 class="mt-4 mb-4">Pupose: {{ detail.purpose }}</h5>
                <h5>Area: {{ detail.size }} {{ detail.unit }}</h5>
                <h5 class="mt-4">Price: {{ detail.price }}</h5>
            </div>
            <div class="col-lg-6">
                <h5>Bathrooms: {{ detail.bathroom }}</h5>
                 <h5 class="mt-4 mb-4">Bedrooms: {{ detail.bedrooms }}</h5>
                <h5>Uploaded: {{ detail.timestamp|naturaltime }}</h5>

                <h5 class="mt-4">Location: {{ detail.address }}</h5>

            </div>

        </div>
    <div class="p-4" style="background-color: rgba(169,169,169,0.9)">
        <h4>Description:</h4>
        <p class="mt-3 font">{{ detail.description }}</p>
    </div>

    </div>
{% endblock %}

seller/templates/seller/password.html
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block content %}
    <form action="" method="POST" class="container p-3 mt-5" style="width: 40%;color: white">
    <legend class="text-center"><h2>Change Password</h2></legend>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Change" class="btn btn-success">
    </form>
{% endblock %}

seller/templates/seller/seller_extension.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_jquery %}
{% bootstrap_javascript %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/seller.css'%}">

</head>
<body>
<div id="seller-home">
<div id="transparent">
   <div class="navbar ">
        <h1 id="h1" style="width: 70%;margin: auto;">REMS</h1>
       {% if user.is_staff %}
           <p class="m-0 mr-4 get-display"><a href="{% url 'management:admin_home' %}">Admin</a></p>
       {% endif %}
        <p class="m-0 mr-4 get-display"><a href="{% url 'seller:passwords' %}">Change password</a></p>
       <p class="m-0 mr-5 get-display"><a href="{% url 'account:logout' %}">Logout</a></p>
    </div>
   <div class="navbar p-2 row m-0 get-display" style="background-color: rgba(124,122,122,.525);" >

       <h3 id="sell-set" class="text-right col-sm-2">Sell          ></h3>
        <h6  class="m-0 p-2 col-lg-1.5"><a href="{% url 'seller:Approve' %}">Approved</a></h6>
        <h6  class="m-0 p-2 col-lg-1.5" ><a href="{% url 'seller:Sold' %}">Sold</a></h6>
        <h6  class="m-0 p-2 col-lg-1.5"><a href="{% url 'seller:pending' %}">Pending</a></h6>
        <h6  class="m-0 p-2 col-lg-sm-1.5"><a href="{% url 'seller:Reject' %}">Not approved</a></h6>
        <h6  class="m-0 p-2 mr-3 border rounded col-lg-1.5 w_display">
            <a href="{% url 'seller:create_property' %}">Add property</a>
        </h6>
        <h6 id="setting-margin" class="m-0 col-lg-4 text-right w_display">
            <a href="{% url 'seller:buyer_home' %}">Switch to Buyer mode</a></h6>
   </div>
    <div style="width:fit-content;background-color: white;color:black;border-radius: 8px;position:sticky;top: 5%;z-index: 2"
         class="ml-5">

    <h3 id="btn-1" style="font-size: 30px" class="p-2 ">
        Menu
        <img src=../../../media/css_styles/list-ul-solid.svg alt="list" style="height: 40px">
    </h3>
    </div>

    <div class="row m-0 fade-out" style="min-height:110vh" id="side-menu">
        <div class="col-sm-10 bg-dark p-5" >
        <div style="display: flex">
            <h1 class="m-0 p-5" style="width: 90%">REMS</h1>
            <h3 class="p-5"><span style="font-size: 30px" id="btn" class=" p-3 btn btn-danger">X</span></h3>
        </div>

        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:Approve' %}">Approved</a></h6>
        <h6  class="m-0 p-5 border-bottom" ><a href="{% url 'seller:Sold' %}">Sold</a></h6>
        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:pending' %}">Pending</a></h6>
        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:Reject' %}">Not approved</a></h6>
        <h6  class="m-0 p-5 border-bottom">
            <a href="{% url 'seller:create_property' %}">Add property</a>
        </h6>
        <h6 class="m-0 p-5 border-bottom">
            <a href="{% url 'seller:buyer_home' %}">Switch to Buyer mode</a></h6>
       {% if user.is_staff %}
           <h6 class="m-0 p-5 border-bottom"><a href="{% url 'management:admin_home' %}">Admin</a></h6>
       {% endif %}
        <h6 class="m-0 p-5 border-bottom"><a href="{% url 'seller:passwords' %}">Change password</a></h6>
       <h6 class="m-0 p-5 border-bottom"><a href="{% url 'account:logout' %}">Logout</a></h6>

        </div>
    </div>


{% block body %}
    <div class="container mt-5 text-center">
        <h1>
            Start selling now!
        </h1>
        <h2><a href="{% url 'seller:create_property' %}">Click here to add property</a></h2>
    </div>
{% endblock %}
    </div>
</div>

<div class="bg-dark p-4" style="color: white ">
    <div class="row m-0">
        <div class="col-lg-6">
            <h2 class="font2">Connect with us!</h2>
            <img id="footer-icon" src=../../../media/css_styles/facebook-brands.svg alt="fb">
            <img id="footer-icon" class="ml-3 mr-3" src=../../../media/css_styles/twitter-brands.svg alt="tw">
            <img id="footer-icon" src=../../../media/css_styles/github-brands.svg alt="git">

{#            <i class="fab fa-facebook" style="font-size: xx-large"></i>#}
{#            <i class="fab fa-twitter ml-3 mr-3" style="font-size: xx-large"></i>#}
{#            <i class="fab fa-github" style="font-size: xx-large"></i>#}
            <h2 class="mt-3 font1">About us!</h2>
            <p class="font3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aut dicta doloremque eos, maiores nisi totam? Accusantium, amet atque autem consectetur deleniti expedita explicabo ipsum magni porro quisquam vero voluptatem.</p>
        </div>
        <div class="col-lg-6">
            <h2 class="font1">Need help!</h2>
            <h3 class="font2">Fill out this <a style="color:dodgerblue;" href="{% url 'seller:index' %}">form</a> and we'll get back to you ASAP</h3>
            <div class="row m-0 mt-3">
                 <div class="col-sm-6">
                    <h4 class="font2">Contact us at</h4>
                    <p class="font3">923115186xxx</p>
                </div>

                <div class="col-sm-6">
                    <h4 class="font2">Email us at</h4>
                    <p class="font3">configteam@netlify.com</p>
                </div>
            </div>
        </div>
    </div>
    <div class="m-0 mt-4 border-top">
        <p class="m-0 text-center p-3 font3">All font icons are property of fontawesome <a href="https://fontawesome.com/">Visit them here</a></p>
    </div>
    <div class="border-top p-3">
        <p class="text-center font3">Copyright &copy;</p>
    </div>
</div>

<script src="../../../static/js/index.js"></script>
</body>
</html>

seller/templates/seller/sellercreate.html
{% extends 'seller/seller_extension.html' %}
{% load  bootstrap4 %}
{% block body %}
    <div class="container mt-5 font-weight-bold" style="width: 40%">
        <form method="POST">
            <legend class="text-center"><h2>Add your property</h2></legend>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-success" value="Add">
        </form>
    </div>
{% endblock %}