account/urls.py
from django.urls import path,include
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import PasswordResetConfirmView,\
    PasswordResetCompleteView,PasswordResetView,PasswordResetDoneView
app_name='account'

# all url patterns for this app mostly contains the login,signup,reset,forget urls
urlpatterns=[
    path('login',LoginHelpView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('',home,name='home'),
    path('signup/<slug:slug>',SignUpView.as_view(),name='signup'),
    path('reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('password_reset_done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete')
]

management/urls.py
from django.urls import path

from .views import *
app_name='management'

urlpatterns=[
    path('',PropertyHome,name='admin_home'),
    path('list-properties/',PropertyList.as_view(),name='All'),
    path('list-properties-approve-admin/',PropertyList.as_view(),name='Approve'),
    path('list-properties-sold-admin/', PropertyList.as_view(), name='Sold'),
    path('list-properties-reject-admin/', PropertyList.as_view(), name='Reject'),
    path('list-properties-pending-admin/', PropertyList.as_view(), name='Pending'),
    path('list-property-houses-admin/',TypeProperty.as_view(),name='Houses'),
    path('list-property-plot-admin/', TypeProperty.as_view(), name='Plot'),
    path('list-property-Commercial-admin/', TypeProperty.as_view(), name='Commercial'),
    path('admin-approve/<int:pk>/',AdminApprovalProperty.as_view(),name='approve'),
    path('admin-reject/<int:pk>/',AdminApprovalProperty.as_view(),name='reject'),
    path('admin-sold-property/<int:pk>/',AdminApprovalProperty.as_view(),name='sold'),
    path('admin-delete/<int:pk>/',DeleteView.as_view(),name='delete'),
    path('seller-list/',PersonList.as_view(),name='seller'),
    path('buyer-list/',PersonList.as_view(),name='buyer'),
    # path('search/',request1,name='nothing')
]

realEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler500,handler404
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('seller/',include('seller.urls')),
    path('admin-dashboard/',include('management.urls')),
    path('',include('django.contrib.auth.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from .views import *
app_name='seller'

urlpatterns=[
    path('passwords-change/',PasswordsChange.as_view(),name='passwords'),
    path('sellercreate/',SellerCreate.as_view(),name='create_property'),
    path('list-property-approved/',SellerListSold.as_view(),name='Approve'),
    path('list-property-pending/',SellerListSold.as_view(),name='pending'),
    path('list-property-not-approved/',SellerListSold.as_view(),name='Reject'),
    path('seller-home/',SellerHome.as_view(),name='seller_home'),
    path('list-sold-property/',SellerListSold.as_view(),name='Sold'),
    path('buyer-home/', BuyerHome.as_view(), name='buyer_home'),
    path('buyer-list-house/',BuyerListPropertiesHouese.as_view(),name='house'),
    path('buyer-list-plot/',BuyerListPropertiesHouese.as_view(),name='plot'),
    path('buyer-list-rent/',BuyerListPropertiesHouese.as_view(),name='rent'),
    path('buyer-list-commercial/',BuyerListPropertiesHouese.as_view(),name='commercial'),
    path('property-detail/<int:pk>/',DetailProperty.as_view(),name='detail'),
    path('buyer-property-detail/<int:pk>/',DetailProperty1.as_view(),name='detail1'),
    path('accepting/',ApprovalView.as_view(),name='redirect'),
    path('mail-sent/',index,name='index')

]

management/models.py
from django.db import models

# Create your models here.

management/views.py
from django.shortcuts import render
from seller.models import *
from account.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import resolve
from seller.filter import *
from django.shortcuts import Http404

# Create your views here.

# filtering functional view for the admin page
def PropertyHome(request):
    if not request.user.is_staff:
        raise Http404
    if request.method == 'GET':
        x = request.GET
        if 'search' in x:
            result = SellerProperty.objects.all()
            search = SellerPropertyFilter(request.GET, queryset=result)
            result = search.qs
            return render(request, 'management/property_home.html', {'search': search, 'result': result})
        else:
            result=SellerProperty.objects.none()
            search = SellerPropertyFilter(request.GET, queryset=result)
            return render(request, 'management/property_home.html', {'search': search})

# property list for admin page
class PropertyList(LoginRequiredMixin, generic.ListView):
    model = SellerProperty
    template_name = 'management/propertyList.html'
    context_object_name = 'list'

    def get_queryset(self):
        if not self.request.user.is_staff:
            raise Http404
        current_url = resolve(self.request.path_info).url_name
        if current_url == 'All':
            return SellerProperty.objects.all()
        else:
            return SellerProperty.objects.filter(approval_seller__request_approval__iexact=current_url)

    def get_context_data(self, *args, **kwargs):
        current_url = resolve(self.request.path_info).url_name
        ctx = super(PropertyList, self).get_context_data(*args, **kwargs)
        ctx['dyno'] = current_url
        ctx['search'] = SellerPropertyFilter()

        return ctx

# list of users present i.e buyers and sellers list
class PersonList(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = 'management/personlist.html'
    context_object_name = 'list'

    def get_queryset(self):
        if not self.request.user.is_staff:
            raise Http404
        current_url = resolve(self.request.path_info).url_name
        return User.object.filter(purpose__iexact=current_url)

    def get_context_data(self, *args, **kwargs):
        current_url = resolve(self.request.path_info).url_name
        ctx = super(PersonList, self).get_context_data(*args, **kwargs)
        ctx['dynamic'] = current_url
        return ctx

# list of property based on its type
class TypeProperty(LoginRequiredMixin, generic.ListView):
    model = SellerProperty
    template_name = 'management/propertyList.html'
    context_object_name = 'list'

    def get_queryset(self):
        if not self.request.user.is_staff:
            raise Http404
        current_url = resolve(self.request.path_info).url_name
        return SellerProperty.objects.filter(type__iexact=current_url)

    def get_context_data(self, *args, **kwargs):
        ctx = super(TypeProperty, self).get_context_data(*args, **kwargs)
        ctx['dyno'] = resolve(self.request.path_info).url_name

        return ctx

# detail page for approval of property
class AdminApprovalProperty(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('management:All')

    def get(self, request, *args, **kwargs):
        print(self)
        y = self.kwargs.get('pk')
        current_url = resolve(self.request.path_info).url_name
        x = Approve.objects.filter(approval_id=y)

        if x:
            x[0].request_approval = current_url.capitalize()
            x[0].save()
        else:
            Approve.objects.create(request_approval=current_url.capitalize(), approval_id=y)
        return super(AdminApprovalProperty, self).get(request, *args, **kwargs)


# deleting the property from the admin panel
class DeleteView(LoginRequiredMixin,generic.DeleteView):
    model = SellerProperty
    template_name = 'management/deleteview.html'
    context_object_name = 'delete'
    success_url = reverse_lazy('management:All')

management/templates/management/deleteview.html
{% extends 'management/property_home.html' %}
{% block admin %}
    <div style="color: white">
        <form action="" method="POST">
            <legend><h3>Are you sure you want to delete this property?</h3></legend>
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-danger">
            <a href="{% url 'seller:detail' delete.pk %}">cancel</a>
        </form>
    </div>
            <div class=" bg-white mt-3 row m-0" style="color: black;height:fit-content;">
            <div class="col-sm-6 p-0 " ><img src="{{ delete.get_photo_url }}" id="img-size" alt=""></div>
            <div class="col-sm-6">
                <h3 class="mb-5 mt-3">Pkr:{{ delete.price }}</h3>
                <h6>{{ delete.address }}</h6>
                <h4>{{ delete.city }}</h4>
                <h5 style="display: inline-block">{{ delete.type.upper }}-{{ delete.purpose }}</h5>
                <i class="fas fa-ruler-combined ml-5"><span> {{ i.size }} {{ delete.unit }}</span></i>
                <h5 ><a style="color:dodgerblue;" >{{ delete.title }}</a></h5>
                 <p class="m-0">{{ delete.description|truncatewords:10 }}</p>
                <p class="m-0">{{ delete.timestamp }}  </p>

            </div>
        </div>
{% endblock %}

management/templates/management/new.html
{% block check %}
    <div class="mt-4" style="color: white">
      <form id="form" action="{% url 'management:admin_home' %}" method="GET" >
    {{ search.form }}
        <input type="submit" value="Search" class="btn btn-success ml-3 input" name="search">
    </form>
    {% for i in result %}
        <div class=" bg-white mt-3 row m-0" style="color: black;height:fit-content;">
            <div class="col-lg-6 p-0 " ><img src="{{ i.get_photo_url }}" id="img-size" alt=""></div>
            <div class="col-lg-6 p-4" id="actual-property">
                <h3 class="mb-5 mt-3">Pkr:{{ i.price }}</h3>
                <h6 class="p-2">{{ i.address }}</h6>
                <h4 class="p-2">{{ i.city }}</h4>
                <h5 style="display: inline-block" class="p-2">{{ i.type.upper }}-{{ i.purpose }}</h5>
                <img style="height:35px" class="mb-3 ml-2 p-2" src="../../../media/css_styles/ruler-combined-solid.svg" alt="">
                <h6 style="display: inline;width: fit-content;"> {{ i.size }} {{ i.unit }}</h6>
                <h5 ><a style="color:dodgerblue;" href="{% url 'seller:detail' i.pk %}">{{ i.title }}</a></h5>
                 <h6 class="m-0 p-2">{{ i.description|truncatewords:10 }}</h6>
                <h6 class="m-0 p-2">{{ i.timestamp }}  </h6>

            </div>
        </div>



    {% endfor %}
    </div>

{% endblock %}

management/templates/management/personlist.html
{% extends 'management/property_home.html' %}
{% block admin %}
    <div style="color: white">
        <h1 class="text-center">Total {{ dynamic }}: {{ list.count }}</h1>

    </div>
    <div class="row p-3" style="color: white">
        <div class="col-sm-6 text-center">
            <h2 class="border-bottom p-2 font">Username</h2>
            {% for i in list %}
                <p class="border-bottom p-2 font">{{ i.username }}</p>
            {% endfor %}
        </div>
    <div class="col-sm-6 text-center ">
        <h2 class="border-bottom p-2 font">Email</h2>
        {% for i in list %}
            <p class="border-bottom p-2 font">{{ i.email }}</p>
        {% endfor %}
    </div>
    </div>

{% endblock %}

management/templates/management/propertyList.html
{% extends 'management/property_home.html' %}

{% block admin %}
    <h2 id="h1" class="text-center" style="color: white">{{ dyno }} property list</h2>
    {% block check %}
        {% include 'management/new.html' %}

    {% endblock %}
    {% if list %}
    {% for i in list %}
        <div class=" bg-white mt-3 row m-0" style="color: black;height:fit-content;">
            <div class="col-lg-6 p-0 " ><img src="{{ i.get_photo_url }}" id="img-size" alt=""></div>
            <div class="col-lg-6 " id="actual-property">
                <h3 class="mb-5 mt-3">Pkr:{{ i.price }}</h3>
                <h6>{{ i.address }}</h6>
                <h4>{{ i.city }}</h4>
                <h5 style="display: inline-block">{{ i.type.upper }}-{{ i.purpose }}</h5>
                <img style="height:35px" class="mb-3 ml-2 p-2" src="../../../media/css_styles/ruler-combined-solid.svg" alt="">
                <h6 style="display: inline;width: fit-content;"> {{ i.size }} {{ i.unit }}</h6>                <h5 ><a style="color:dodgerblue;" href="{% url 'seller:detail' i.pk %}">{{ i.title }}</a></h5>
                 <h6 class="m-0">{{ i.description|truncatewords:10 }}</h6>
                <h6 class="m-0">{{ i.timestamp }}  </h6>

            </div>
        </div>
    {% endfor %}
    {% else %}
        <div class="text-center mt-5" style="color:white;">
            <h2>Nothing {{ dyno }} yet!!</h2>
        </div>
    {% endif %}

{% endblock %}

management/templates/management/property_home.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_jquery %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" href="{% static 'css/seller.css' %}">
    </head>
<body>

    <div id="property-bg" >
    <div id="transparent">

        <div class="navbar" style="color: white">
            <h1 id="h1" style="width: 70%;color: white">
                REMS
            </h1>

            <p class="get"><a style="color: white" href="{% url 'seller:buyer_home' %}">Buyer home</a></p>
            <p class="get-dwedcisplay"><a style="color: white" href="{% url 'seller:passwords' %}">Change password</a></p>
            <p class="get-displwdcay"><a style="color: white" href="{% url 'account:logout' %}">Logout</a></p>
        </div>
        <div style="width:fit-content;background-color: white;color:black;border-radius: 8px;position:sticky;top: 5%;z-index: 2"
         class="ml-5">

    <h3 id="btn-1" style="font-size: 30px" class="p-2 ">
        Menu
        <img src=../../../media/css_styles/list-ul-solid.svg alt="list" style="height: 40px">
    </h3>
    </div>
    <div class="row m-0 p-2 fade-out" style="height:220vh" id="side-menu">
        <div class="col-sm-10 bg-dark p-5" >
            <div>
        <div style="display: flex">
            <h1 class="m-0 p-5" style="width: 90%;color: white">REMS</h1>
            <h3 class="p-5"><span style="font-size: 30px" id="btn" class=" p-3 btn btn-danger">X</span></h3>
        </div>

        <h6  class="m-0 p-5 border-bottom"><a style="color: white"  href="{% url 'management:seller' %}">
                        Seller
                    </a></h6>
        <h6  class="m-0 p-5 border-bottom"><a style="color: white"  href="{% url 'management:buyer' %}">
                        Buyer
                    </a></h6>
        <h6  class="m-0 p-5 border-bottom" ><a href="{% url 'seller:house' %}">Houses</a></h6>

        <h6  class="m-0 p-5 border-bottom" ><a href="{% url 'seller:plot' %}">Plots</a></h6>

        <h6  class="m-0 p-5 border-bottom"><a href="{% url 'seller:rent' %}">Rent</a></h6>
        <h6  class="m-0 p-5 border-bottom" ><a href="{% url 'seller:plot' %}">Plots</a></h6>
        <h6  class="m-0 p-5 border-bottom" >  <a style="color: white" href="{% url 'management:Approve' %}">Approved</a>
</h6>
        <h6  class="m-0 p-5 border-bottom" ><a style="color: white" href="{% url 'management:Reject' %}">Rejected</a></h6>
        <h6  class="m-0 p-5 border-bottom" ><a style="color: white" href="{% url 'management:Pending' %}">Pending</a></h6>
        <h6  class="m-0 p-5 border-bottom" ><a style="color: white" href="{% url 'management:Sold' %}">Sold</a></h6>


</div>
        </div>
    </div>
{#    {% block check %}#}
{#        {% include 'management/new.html' %}#}
{#            <form method="GET" class="container" style="color: white">#}
{#                {% csrf_token %}#}
{#            <p style="display: inline">{{ search.form }}</p>#}
{#            <input type="submit" value="Search" class="btn btn-success">#}
{#        </form>#}
{#        {{ result }}#}
{#    {% endblock %}#}

        <div class="row m-0 mx-auto" style="width: 80%;">
            <div class="col-lg-4 bg-dark p-5 get-display" style="width: 50%">
                <div>
                    <h5  class="border-bottom p-3"><a style="color: white"  href="{% url 'management:seller' %}">
                        Seller
                    </a></h5>
                    <h5 class="mt-4 border-bottom p-3"><a style="color: white"  href="{% url 'management:buyer' %}">
                        Buyer
                    </a></h5>
                    <div style="color: white" class="mt-4">
                        <h5 class="border-bottom p-3"style="color: white" >Type</h5>
                        <div class="container" >
                            <p class="p-2 mt-4 border-bottom">
                                <a style="color: white" href="{% url 'management:Houses' %}">House</a>
                            </p>
                            <p class="p-2 border-bottom">
                                <a style="color: white" href="{% url 'management:Plot' %}">Plot</a>
                            </p>
                            <p class="p-2 border-bottom">
                                <a style="color: white" href="{% url 'management:Commercial' %}">Commercial</a>
                            </p>
                        </div>
                    </div>
                    <div>
                        <h5 class="mt-4 border-bottom p-3"><a style="color: white"  href="{% url 'management:All' %}">
                            Property</a></h5>
                        <div class="container" >
                            <p class="border-bottom p-3 mt-4">
                                <a style="color: white" href="{% url 'management:Approve' %}">Approved</a>
                            </p>
                            <p class="border-bottom p-3">
                                <a style="color: white" href="{% url 'management:Reject' %}">Rejected</a>
                            </p>
                            <p class="border-bottom p-3">
                                <a style="color: white" href="{% url 'management:Pending' %}">Pending</a>
                            </p>
                            <p class="border-bottom p-3">
                                <a style="color: white" href="{% url 'management:Sold' %}">Sold</a>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 m-0" id="width2">
                {% block admin %}
                    <div class="div" style="color:white;">
                        <h1>Welcome to the admin dashboard</h1>
                    </div>
                    {% block check %}
                        {% include 'management/new.html' %}
                    {% endblock %}
                {% endblock %}

            </div>
        </div>
        </div>

    </div>

</body>

<script src="../../../static/js/index.js"></script>



</html>