account/urls.py
from django.urls import path,include
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import PasswordResetConfirmView,\
    PasswordResetCompleteView,PasswordResetView,PasswordResetDoneView
app_name='account'

# all url patterns for this app mostly contains the login,signup,reset,forget urls
urlpatterns=[
    path('login',LoginHelpView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('',home,name='home'),
    path('signup/<slug:slug>',SignUpView.as_view(),name='signup'),
    path('reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('password_reset_done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete')
]

realEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler500,handler404
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('seller/',include('seller.urls')),
    path('admin-dashboard/',include('management.urls')),
    path('',include('django.contrib.auth.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from .views import *
app_name='seller'

urlpatterns=[
    path('passwords-change/',PasswordsChange.as_view(),name='passwords'),
    path('sellercreate/',SellerCreate.as_view(),name='create_property'),
    path('list-property-approved/',SellerListSold.as_view(),name='Approve'),
    path('list-property-pending/',SellerListSold.as_view(),name='pending'),
    path('list-property-not-approved/',SellerListSold.as_view(),name='Reject'),
    path('seller-home/',SellerHome.as_view(),name='seller_home'),
    path('list-sold-property/',SellerListSold.as_view(),name='Sold'),
    path('buyer-home/', BuyerHome.as_view(), name='buyer_home'),
    path('buyer-list-house/',BuyerListPropertiesHouese.as_view(),name='house'),
    path('buyer-list-plot/',BuyerListPropertiesHouese.as_view(),name='plot'),
    path('buyer-list-rent/',BuyerListPropertiesHouese.as_view(),name='rent'),
    path('buyer-list-commercial/',BuyerListPropertiesHouese.as_view(),name='commercial'),
    path('property-detail/<int:pk>/',DetailProperty.as_view(),name='detail'),
    path('buyer-property-detail/<int:pk>/',DetailProperty1.as_view(),name='detail1'),
    path('accepting/',ApprovalView.as_view(),name='redirect'),
    path('mail-sent/',index,name='index')

]

templates/home.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_jquery %}
<html>
<head>
    <title>
        REMS
    </title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<div id="bg-home">
    <div id="trans">
    <div class="navbar">
        <h1><a style="color: white;text-decoration: none" href="{% url 'account:home' %}">REMS</a></h1>
    </div>
    {% block content %}
        <div id="home-page" class="mx-auto text-center">
        <h1 class="p-3 font-weight-light" style="font-size: 80px">Welcome to REMS git</h1>
            <h1 class="p-2 font-weight-bolder" style="font-size: 60px">Buy or sell your property</h1>
            <h1 class="font-weight-bolder" style="font-size: 60px">Register Yourself as:</h1>
            <p class="btn btn-primary"><a style="font-size: x-large" href="{% url 'account:signup' buyer %}">Buyer</a></p>
            <p class="btn btn-primary ml-4"><a style="font-size: x-large" href="{% url 'account:signup' seller %}">Seller</a></p>
            <small style="display:block">Already have an account <a href="{% url 'account:login' %}">Login</a></small>
        </div>
    {% endblock %}
    </div>
</div>
<div class="bg-dark p-4" style="color: white ">
    <div class="row m-0">
        <div class="col-lg-6">
            <h2 class="font2">Connect with us!</h2>
            <img id="footer-icon" src=../media/css_styles/facebook-brands.svg alt="fb">
            <img id="footer-icon" class="ml-3 mr-3" src=../media/css_styles/twitter-brands.svg alt="tw">
            <img id="footer-icon" src=../media/css_styles/github-brands.svg alt="git">

{#            <i class="fab fa-facebook" style="font-size: xx-large"></i>#}
{#            <i class="fab fa-twitter ml-3 mr-3" style="font-size: xx-large"></i>#}
{#            <i class="fab fa-github" style="font-size: xx-large"></i>#}
            <h2 class="mt-3 font1">About us!</h2>
            <p class="font3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aut dicta doloremque eos, maiores nisi totam? Accusantium, amet atque autem consectetur deleniti expedita explicabo ipsum magni porro quisquam vero voluptatem.</p>
        </div>
        <div class="col-lg-6">
            <h2 class="font1">Need help!</h2>
            <h3 class="font2">Fill out this <a style="color:dodgerblue;" href="{% url 'seller:index' %}">form</a> and we'll get back to you ASAP</h3>
            <div class="row m-0 mt-3">
                 <div class="col-sm-6">
                    <h4 class="font2">Contact us at</h4>
                    <p class="font3">923115186xxx</p>
                </div>

                <div class="col-sm-6">
                    <h4 class="font2">Email us at</h4>
                    <p class="font3">configteam@netlify.com</p>
                </div>
            </div>
        </div>
    </div>
    <div class="m-0 mt-4 border-top">
        <p class="m-0 text-center p-3 font3">All font icons are property of fontawesome <a href="https://fontawesome.com/">Visit them here</a></p>
    </div>
    <div class="border-top p-3">
        <p class="text-center font3">Copyright &copy;</p>
    </div>
</div>



</body>

</html>